# name of the workflow
name: CI

# Trigger on pushes or pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Defines a job named "build"
  build:
    # Run this job on the latest Ubuntu virtual environment
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout your repository so the runner has your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Set up Python 3.9 on the runner
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3) Install project dependencies in a virtual environment
      - name: Install dependencies
        run: |
          python -m venv venv         # Create a new virtual environment
          source venv/bin/activate    # Activate the virtual environment
          python -m pip install --upgrade pip
          pip install -e .            # Install your package in editable mode

      # 4) Run the test suite with pytest
      - name: Run test suite
        run: |
          source venv/bin/activate    # Ensure the venv is active
          pytest -q --disable-warnings --maxfail=1  # Execute tests
