# name of the workflow
name: CI

# Trigger workflow on pushes and pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout your repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Cache pip packages for faster installs
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      # 4) Install dependencies and test tools
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip          # Upgrade pip
          pip install -e .                            # Install project in editable mode
          pip install pytest flake8 pytest-cov        # Install pytest, flake8, and pytest-cov

      # 5) Lint code with flake8, but override defaults for CI
      - name: Lint code
        run: |
          flake8 . \
            --max-line-length=100 \
            --ignore=E203,E266,E302,E305,W293 \
            --extend-ignore=F401,E501
                               # Check code style and catch errors early

      # 6) Run test suite with coverage
      - name: Run tests with coverage
        run: pytest --cov=expense_tracker -q --disable-warnings --maxfail=1  
        # Execute tests and measure coverage on the 'expense_tracker' module