# name of the workflow
name: CI

# Trigger on pushes and pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout your repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Set up Python 3.x on the runner
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Create & activate a virtual environment, install deps
      - name: Install dependencies
        run: |
          python -m venv venv                  # create venv
          source venv/bin/activate             # activate venv
          python -m pip install --upgrade pip  # upgrade pip
          pip install -e .                     # install your package
          pip install pytest                   # install pytest for tests

      # 4) Run pytest to validate the code
      - name: Run test suite
        run: |
          source venv/bin/activate             # ensure venv is active
          pytest -q --disable-warnings --maxfail=1